<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	<RuntimeIdentifiers>linux-x64;linux-arm64</RuntimeIdentifiers>
	<PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
		<PackageReference Include="AWSSDK.Athena" Version="4.0.1.9" />
		<PackageReference Include="AWSSDK.Core" Version="4.0.0.15" />
		<PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="4.0.2" />
		<PackageReference Include="Flurl.Http" Version="3.2.4" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.3" />
	</ItemGroup>

</Project>
