<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
	<DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
	<RuntimeIdentifiers>linux-x64;linux-arm64</RuntimeIdentifiers>
	<PublishReadyToRun>true</PublishReadyToRun>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EventLog.Middleware\EventLog.Middleware.csproj" />
  </ItemGroup>

</Project>
